# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QlWv8f3_zMZAtHccm2jM2f9t0qHVw4a4
"""

#---------Libraries------------
# We need pandas to handle... pretty much everything to do with DataFrame
# numpy is used for calculating entropy (specifically the sum an log2 functions)
# train_test_split is used to split the dataset into training and testing

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# This is the source file for the data we're going to use. It's a manufacturing
# log, with many measurement columns and outputs to predict

csv_file_path = "continuous_factory_process.csv"
df = pd.read_csv(csv_file_path, header=0)

#df.info()
#df.describe() # This is a useful function

#------Trim dataset--------#
# Stage2 was described as noisy in the data description, and less reliable for
# predictions, so we'll focus on Stage1 measurements.
# Output columns are the ones we want to predict. Actual columns are the
# measurements. There are also setpoint columns, which are the expected outputs.
# We're basically going to ignore those, because we're making our own
# predictions. All other columns are going to be trimmed!

# Create an empty list to store Stage1 output columns
stage1_columns = []
for col in df.columns:
    if 'Stage1.Output' in col and 'Actual' in col:
        stage1_columns.append(col)

# Create another list for all other 'Actual' columns excluding Stage2 and Output
actual_columns = []
for col in df.columns:
    if 'Actual' in col and 'Stage1' not in col and 'Stage2' not in col and 'Output' not in col:
        actual_columns.append(col)

relevant_columns = stage1_columns + actual_columns

# Keep only the relevant columns in the trimmed DataFrame
df_trimmed = df[relevant_columns]

# Print a few lines to make sure it looks fine
#print(df_trimmed.head())

#------Discretize Data----------
# Since we don't have a great handle on the data (other than the description)
# we'll rely on a quartile discretization approach, which can be
# applied to all predictor and output columns

def discretize_columns(df, columns):
    final_columns = []  # Successfully discretized columns

    # This was an issue I kept running into. One specific column that will be
    # named and shamed ('Machine5.Temperature3.C.Actual') doesn't have enough
    # variance to be binned properly, so it gums up everything else it touches.
    # It's my problem column, and I basically trim it.
    problem_columns = []

    # Define bin edges based on quartiles
    for column in columns:
        bins = [
            df[column].min(),  # Minimum value
            df[column].quantile(0.25),  # 25th percentile
            df[column].quantile(0.75),  # 75th percentile
            df[column].max()  # Maximum value
        ]

        # Ensure bins edges are unique to avoid errors. If I don't do this, then
        # Python dies and says it can't bin things with overlapping bin edges.
        unique_bins = sorted(set(bins))

        if len(unique_bins) > 2:  # Ensure at least 3 bins for meaningful categories
            labels = ['Low', 'Medium', 'High']  # These seemed as good of labels as any
            discrete_column = f"{column}_Discrete"

            # This is a handy little function that is used to bin data! Thanks
            # pandas, you make this project possible. We want to make new
            # columns so we can still reference the raw data if we need to, or
            # the discretized version, so we'll name it {column}_Discrete.
            # This function takes the DataFrame column we want to bin, what the
            # bin edges are (defined above), what the labels for those bins are
            # (the labels need to be the number of bin edges - 1), and a setting
            # to include either the lowest or highest value as a bin edge. I
            # went with lowest
            df[discrete_column] = pd.cut(
                df[column], bins=unique_bins, labels=labels[:len(unique_bins) - 1], include_lowest=True
            )
            final_columns.append(column)
        else:
            problem_columns.append(column)

    return final_columns, problem_columns

#--------Validate Discretization----------
def validate_discrete_columns(columns):
    # Count the number of instances in each category for discretized columns
    # and display the first few rows of the original and discretized columns side by side
    for column in columns:
        discrete_column = f"{column}_Discrete"
        if discrete_column in df.columns:  # Ensure the discretized column exists
            print(f"Category counts for {discrete_column}:")
            print(df[discrete_column].value_counts())
            print(df[[column, discrete_column]].head())

#-----------Decision Tree Functions---------------

# Calculates entropy. Says what it does right on the tin. Counts the instances
# of values within the data, and divides it by the length of the data to get the
# probability of the values, then hits it with the sum(p * log2(p)).
def calculate_entropy(data):
    counts = data.value_counts()
    probabilities = counts / len(data)
    probabilities = probabilities[probabilities > 0]  # Filter out zero probabilities
    entropy = -np.sum(probabilities * np.log2(probabilities))
    return entropy


# Information Gain. Takes the entropy of an attribute and the entropy of the
# entire column and divides them to get the weight of that attribute. Multiply
# by the weight to get weighted entropy, subtract from overall entropy, and
# you've got a result!
def calculate_information_gain(df, target_column, predictor_column):
    # Calculate overall entropy
    overall_entropy = calculate_entropy(df[target_column])

    # Calculate weighted entropy for splits
    weighted_entropy = 0
    for category in df[predictor_column].unique():
        subset = df[df[predictor_column] == category]
        subset_entropy = calculate_entropy(subset[target_column])
        weight = len(subset) / len(df)
        weighted_entropy += weight * subset_entropy

    # Information gain is the reduction in entropy
    information_gain = overall_entropy - weighted_entropy
    return information_gain

# Super simple function to determine best splits based on entropy and info gain.
# We loop through the columns (making sure the column actually exists in the
# DataFrame, because we might have trimmed it when we discretized the data),
# and calculate the info gain on that column. If it's the best info gain, then
# we return that column and gain value.
def find_best_split(df, target_column, predictor_columns):
    best_gain = 0
    best_column = None

    for column in predictor_columns:
        if column not in df.columns:  # Ensure column exists
            print(f"Warning: {column} does not exist in DataFrame, skipping.")
            continue

        gain = calculate_information_gain(df, target_column, column)
        if gain > best_gain:
            best_gain = gain
            best_column = column

    return best_column, best_gain

# Building the trees! This is the meat and potatoes of the whole thing.
# We pass in a max_depth, because the tree becomes pretty unweildy after 5
# layers. I started with 3, and that went well, but 5 upped accuracy by about
# 10% overall, and only added about 2 minutes to the runtime.
def build_tree(df, target_column, predictor_columns, depth=0, max_depth=5):

    #If we reach our max depth, or if we find a node, make a leaf!
    if depth >= max_depth or len(df[target_column].unique()) == 1:

        # This just counts the number of unique values. Normalizing it divides
        # the count by the number of rows to produce a percentage
        counts = df[target_column].value_counts(normalize=True)
        majority_class = counts.idxmax()  # Most frequent index (bin label)
        confidence = counts.max()  # Proportion of majority class (value)
        leaf = {"Prediction": majority_class, "Confidence": confidence}
        #print(f"Leaf Node Created: {leaf}")  # Debugging print

        # Return the leaf, which is a dict of a bin label, and a confidence
        return leaf

    best_column, best_gain = find_best_split(df, target_column, predictor_columns)

    # If we can't find anymore splits to make, then we're probably done with
    # this branch, so we should return what we have.
    if not best_column or best_gain == 0:
        counts = df[target_column].value_counts(normalize=True)
        majority_class = counts.idxmax()
        confidence = counts.max()
        leaf = {"Prediction": majority_class, "Confidence": confidence}
        #print(f"Leaf Node Created (No Split): {leaf}")  # Debugging print
        return leaf

# Trees do like recursion. Here, we're initializing what the split attribute
# will be. We then loop though each of the bin labels for each column (High,
# Medium and Low), and create a subset of the data, based on when the value
# of the current bin label is equal to the value of the best column. We need
# to do this to make sure the next tree we build will be using a subset of the
# data, instead of... all of it. Which would be not useful.
    tree = {best_column: {}}
    for category in df[best_column].unique():
        subset = df[df[best_column] == category]
        # We then recurse back up, with the new subset of data, and increased
        # depth
        tree[best_column][category] = build_tree(
            subset, target_column, predictor_columns, depth + 1, max_depth
        )

    return tree

#--------Construct Predictions Logic-----------

def predict_with_confidence(tree, row):
    # Check if current tree is a leaf node
    # The trees are stored as dictionaries, with prediction and confidence in the
    # leaf nodes. If it doesn't have those values in the node, then we don't have
    # the ability to predict anything yet!
    # Also, if I didn't check for is tree a dict, it would fail on the branches
    # when trying to evaluate them, so I need to add that check on both cases.
    if isinstance(tree, dict) and "Prediction" in tree and "Confidence" in tree:
        return tree["Prediction"], tree["Confidence"]

    # Otherwise, process branch nodes
    if isinstance(tree, dict):
        root = next(iter(tree))  # Get the feature to split on
        value = row.get(root, None)  # Fetch the feature value from the row
        subtree = tree[root].get(value, None)  # Navigate to the correct branch

        # Depending on the data splits we have cases where there isn't an instance
        # of a particular attribute having a certain value, so we have no way
        # to predict what to do with it. In that case, we just return it as a
        # 0 confidence prediction of nothing instead of failing horribly.
        if subtree is None:
            print(f"Missing branch for value '{value}' in feature '{root}'")  # Debugging print
            return None, 0  # Handle missing branches gracefully

        # Recurse to the next branch to evaluate it!
        return predict_with_confidence(subtree, row)

    # If the tree doesn't match expected structures, handle as invalid
    # I haven't seen this happen lately, but just in case I figured it wouldn't
    # be a bad idea to have some security. If a bad structure comes along,
    # return it as a 0 confidence prediction of nothing!
    print(f"Invalid tree structure encountered: {tree}")  # Debugging print
    return None, 0

#---------Testing and Validation-----------#

# Split data into training, testing and validation sets. Current split is
# 30% of data going to testing and validation, 50% of that (15% total) going to
# validation, which leaves 70% data for training the tree.

def split_data(df, target_column, test_size=0.3, validation_size=0.5):

    # Split into training and temp (testing + validation)
    # random_state value ensure random split is seeded with a constant for
    # reproducability. We can omit that for a more random split result
    train_df, temp_df = train_test_split(df, test_size=test_size, random_state=1)

    # Split temp into testing and validation
    test_df, val_df = train_test_split(temp_df, test_size=validation_size, random_state=1)

    return train_df, test_df, val_df

def evaluate_single_tree(decision_tree, df, output_column, actual_columns):
    print(f"Evaluating predictions for: {output_column}")

    # Generate predictions
    # Had to learn about lambda and apply() here. lambda specifies an inline function
    # apply() will do that lambda function to either columns or rows of the
    # DataFrame. axis=1 means it specifies rows, and the row keyword after
    # lambda is a variable declaration. Basically, for each row in the DataFrame
    # pass in the decision tree and the current row into the predict function
    predictions = df.apply(lambda row: predict_with_confidence(decision_tree, row), axis=1)

    # Compile results
    # Make a copy of the output column we're evaluating predictions against
    result_df = df[[f"{output_column}_Discrete"]].copy()
    # Run through each item in the predictions array we just constructed and grab
    # the prediction values ("low", "medium", etc...)
    result_df['Predicted'] = predictions.apply(lambda x: x[0])
    # Do the same as above, but with the confidence scores of the predictions
    result_df['Confidence'] = predictions.apply(lambda x: x[1])

    # Add predictor columns
    # This will append the predictor columns related to our predictions
    # into the DataFrame. We don't technically need them, but it provides a
    # trace into why we predicted what we did
    for predictor in [f"{col}_Discrete" for col in actual_columns]:
        result_df[predictor] = df[predictor]

    return result_df

def calculate_accuracy(result_df, target_column):
    # Here we're comparing our predicted result with our output column value
    # If they are equal, it returns 1, which is summed so get a running count of
    # how many predictions were correct
    correct_predictions = (result_df[target_column] == result_df['Predicted']).sum()
    total_predictions = len(result_df)
    # We return the total of correct predictions divided by total predictions
    # to get the percentage accuracy for the output predictions.
    return correct_predictions / total_predictions

# Discretize actual columns (predictor columns)
actual_columns, problem_actual_columns = discretize_columns(df, actual_columns)

print("Actual Columns omitted due to insufficient unique bins:")
print(problem_actual_columns)

# Discretize stage1 columns (output columns)
# we don't need to store these results, as the DataFrame is being manipulated
# directly for these, but I figured I would anyway just in case. For reasons.
discrete_output, problem_stage1_columns = discretize_columns(df, stage1_columns)

print("Stage1 Columns omitted due to insufficient unique bins:")
print(problem_stage1_columns)

#--------Validate Predictor discretization----------

validate_discrete_columns(actual_columns)

#--------Validate Output discretization----------

validate_discrete_columns(stage1_columns)

#---------Main Process--------#
# This will run through each output column, and generate a decision tree
# for it. It will then run the test and validation data through the tree
# to verify thee predictions, and give an accuracy score

testing_accuracies = {}
validation_accuracies = {}

for output_column in stage1_columns:
    print(f"\nProcessing output: {output_column}")

    # Split data for the current output
    train_df, test_df, val_df = split_data(df, target_column=f"{output_column}_Discrete")

    # Build the tree for the current output
    decision_tree = build_tree(
        train_df,
        target_column=f"{output_column}_Discrete",
        predictor_columns=[f"{col}_Discrete" for col in actual_columns],
        max_depth=5  # Adjust as needed
    )

    # Evaluate on testing and validation sets
    test_results = evaluate_single_tree(decision_tree, test_df, output_column, actual_columns)
    val_results = evaluate_single_tree(decision_tree, val_df, output_column, actual_columns)

    # Calculate accuracy for testing and validation
    test_accuracy = calculate_accuracy(test_results, target_column=f"{output_column}_Discrete")
    val_accuracy = calculate_accuracy(val_results, target_column=f"{output_column}_Discrete")

    # Store accuracies
    testing_accuracies[output_column] = test_accuracy
    validation_accuracies[output_column] = val_accuracy

    print(f"Testing Accuracy for {output_column}: {test_accuracy}")
    print(f"Validation Accuracy for {output_column}: {val_accuracy}")

# Print summary of accuracies
print("\nSummary of Testing Accuracies:")
for output, acc in testing_accuracies.items():
    print(f"{output}: {acc}")

print("\nSummary of Validation Accuracies:")
for output, acc in validation_accuracies.items():
    print(f"{output}: {acc}")

#---------Generate Predictions File----------
# Be careful, this file is like 450MB, but does show what the tree looks like
# if you're brave enough, because it sucks to read
def summarize_predictions_all_trees_to_file(decision_trees, df, stage1_columns, actual_columns, filename="tree_predictions.txt"):
    with open(filename, "w") as f:
        for output_column in stage1_columns:
            f.write(f"\nPredictions for {output_column}:\n")

            # Ensure the tree exists
            tree = decision_trees.get(output_column)
            if not tree:
                f.write(f"Warning: No tree found for {output_column}, skipping.\n")
                continue

            # Generate predictions
            predictions = df.apply(lambda row: predict_with_confidence(tree, row), axis=1)

            # Compile results
            result_df = df[[f"{output_column}_Discrete"]].copy()
            result_df['Predicted'] = predictions.apply(lambda x: x[0])
            result_df['Confidence'] = predictions.apply(lambda x: x[1])

            # Include predictor values for readability
            for predictor in [f"{col}_Discrete" for col in actual_columns]:
                result_df[predictor] = df[predictor]

            # Group predictions by predicted output
            for predicted_value in result_df['Predicted'].unique():
                f.write(f"Output -> {predicted_value}:\n")

                # Filter rows where the prediction matches this category
                subset = result_df[result_df['Predicted'] == predicted_value]

                # Extract predictor values per output
                for _, row in subset.iterrows():
                    predictor_values = [f"{col} = {row[col]}" for col in result_df.columns if col not in ['Predicted', 'Confidence', f"{output_column}_Discrete"]]
                    f.write(f"  - {', '.join(predictor_values)}\n")
                f.write("\n")  # Blank line for spacing
    print(f"\nPredictions saved to {filename}")

# Uncomment this to generate the file.
#summarize_predictions_all_trees_to_file(decision_trees, df, stage1_columns, actual_columns)